Repository Spimy/KitaHack-2024, pull requests merged in 2024-01, with the labels that each got.

#6 Add jobs endpoints
  server/src/controllers/jobs.controller.ts
  server/src/controllers/skills.controller.ts
  server/src/database.ts
  server/src/index.ts
  server/src/middleware/auth.middleware.ts
  server/src/routes/jobs.routes.ts
  server/src/routes/skills.routes.ts
  shared/src/types/job.ts
Labels: enhancement

#5 Add post endpoints
  server/.gitignore
  server/src/controllers/posts.controller.ts
  server/src/controllers/users.controller.ts
  server/src/database.ts
  server/src/index.ts
  server/src/routes/posts.routes.ts
  server/src/services/uploader.service.ts
  shared/src/types/post.ts
Labels: enhancement

#8 Homepage
  client/package-lock.json
  client/package.json
  client/src/app/pages/home/home.component.html
  client/src/app/pages/home/home.component.ts
  client/src/app/pages/login/login.component.ts
  client/src/app/shared/authentication.service.ts
  client/src/app/views/home/business-view/business-view.component.css
  client/src/app/views/home/business-view/business-view.component.html
  client/src/app/views/home/business-view/business-view.component.spec.ts
  client/src/app/views/home/business-view/business-view.component.ts
  client/src/app/views/home/landing-view/landing-view.component.css
  client/src/app/views/home/landing-view/landing-view.component.html
  client/src/app/views/home/landing-view/landing-view.component.spec.ts
  client/src/app/views/home/landing-view/landing-view.component.ts
  client/src/app/views/home/user-view/user-view.component.css
  client/src/app/views/home/user-view/user-view.component.html
  client/src/app/views/home/user-view/user-view.component.spec.ts
  client/src/app/views/home/user-view/user-view.component.ts
  client/yarn.lock
  server/package-lock.json
Labels: bug

#10 Add Homepage
  client/src/app/app.component.html
  client/src/app/app.component.ts
  client/src/app/app.routes.ts
  client/src/app/components/footer/footer.component.css
  client/src/app/components/footer/footer.component.html
  client/src/app/components/footer/footer.component.spec.ts
  client/src/app/components/footer/footer.component.ts
  client/src/app/components/header/header.component.css
  client/src/app/components/header/header.component.html
  client/src/app/components/header/header.component.spec.ts
  client/src/app/components/header/header.component.ts
  client/src/app/components/mini-info-card/mini-info-card.component.css
  client/src/app/components/mini-info-card/mini-info-card.component.html
  client/src/app/components/mini-info-card/mini-info-card.component.spec.ts
  client/src/app/components/mini-info-card/mini-info-card.component.ts
  client/src/app/components/summary-card/summary-card.component.css
  client/src/app/components/summary-card/summary-card.component.html
  client/src/app/components/summary-card/summary-card.component.spec.ts
  client/src/app/components/summary-card/summary-card.component.ts
  client/src/app/footer/footer.component.html
  client/src/app/header/header.component.html
  client/src/app/header/header.component.ts
  client/src/app/pages/home/home.component.html
  client/src/app/pages/home/home.component.ts
  client/src/app/pages/login/login.component.ts
  client/src/app/pages/not-found/not-found.component.css
  client/src/app/pages/not-found/not-found.component.html
  client/src/app/pages/not-found/not-found.component.spec.ts
  client/src/app/pages/not-found/not-found.component.ts
  client/src/app/pages/profile/profile.component.ts
  client/src/app/pages/register/register.component.ts
  client/src/app/service/job.service.spec.ts
  client/src/app/service/job.service.ts
  client/src/app/services/authentication.service.ts
  client/src/app/services/job.service.ts
  client/src/app/services/test.service.ts
  client/src/app/services/user-store.service.ts
  client/src/app/services/user.service.ts
  client/src/app/views/home/business-view/business-view.component.html
  client/src/app/views/home/business-view/business-view.component.ts
  client/src/app/views/home/landing-view/landing-view.component.html
  client/src/app/views/home/user-view/user-view.component.html
  client/src/app/views/home/user-view/user-view.component.ts
  client/src/environments/environment.ts
  client/tailwind.config.js
  server/src/controllers/jobs.controller.ts
  server/src/controllers/users.controller.ts
  server/src/index.ts
  shared/src/types/job.ts
  shared/src/types/user.ts
Labels: enhancement

#18 Profile
  client/angular.json
  client/package-lock.json
  client/package.json
  client/src/app/app.config.ts
  client/src/app/app.routes.ts
  client/src/app/components/header/header.component.html
  client/src/app/components/mini-info-card/mini-info-card.component.html
  client/src/app/components/summary-card/summary-card.component.ts
  client/src/app/pages/edit-profile/edit-profile.component.css
  client/src/app/pages/edit-profile/edit-profile.component.html
  client/src/app/pages/edit-profile/edit-profile.component.spec.ts
  client/src/app/pages/edit-profile/edit-profile.component.ts
  client/src/app/pages/job-details/job-details.component.html
  client/src/app/pages/login/login.component.ts
  client/src/app/pages/profile/profile.component.html
  client/src/app/pages/profile/profile.component.ts
  client/src/app/pages/register/register.component.ts
  client/src/app/services/authentication.service.ts
  client/src/app/services/skills.service.ts
  client/src/app/services/user-store.service.ts
  client/src/app/services/user.service.ts
  client/src/app/views/home/business-view/business-view.component.html
  client/src/app/views/home/user-view/user-view.component.html
  client/src/styles.css
  server/src/controllers/posts.controller.ts
  server/src/controllers/skills.controller.ts
  server/src/controllers/users.controller.ts
  server/src/routes/users.routes.ts
  server/src/services/uploader.service.ts
Labels: enhancement

#19 Fetch optimisation
  client/src/app/app.routes.ts
  client/src/app/components/comment/comment.component.html
  client/src/app/components/comment/comment.component.ts
  client/src/app/components/header/header.component.html
  client/src/app/components/header/header.component.ts
  client/src/app/components/post/post.component.html
  client/src/app/components/post/post.component.ts
  client/src/app/pages/applicants/applicants.component.html
  client/src/app/pages/applicants/applicants.component.ts
  client/src/app/pages/create-post/create-post.component.html
  client/src/app/pages/create-post/create-post.component.ts
  client/src/app/pages/edit-profile/edit-profile.component.ts
  client/src/app/pages/forum/forum.component.html
  client/src/app/pages/forum/forum.component.ts
  client/src/app/pages/home/home.component.ts
  client/src/app/pages/job-details/job-details.component.html
  client/src/app/pages/job-details/job-details.component.ts
  client/src/app/pages/jobs/jobs.component.html
  client/src/app/pages/jobs/jobs.component.ts
  client/src/app/pages/post-details/post-details.component.html
  client/src/app/pages/post-details/post-details.component.ts
  client/src/app/pages/profile/profile.component.html
  client/src/app/pages/profile/profile.component.ts
  client/src/app/services/authentication.service.ts
  client/src/app/services/forum.service.ts
  client/src/app/services/job.service.ts
  client/src/app/services/user.service.ts
  client/src/app/views/home/business-view/business-view.component.html
  client/src/app/views/home/business-view/business-view.component.ts
  client/src/app/views/home/user-view/user-view.component.html
  client/src/app/views/home/user-view/user-view.component.ts
  server/src/controllers/jobs.controller.ts
  server/src/controllers/posts.controller.ts
  server/src/controllers/users.controller.ts
  server/src/database.ts
  server/src/global.d.ts
  server/src/middleware/auth.middleware.ts
  server/src/routes/posts.routes.ts
  server/src/routes/users.routes.ts
  server/src/utils/job.util.ts
  server/src/utils/post.util.ts
  server/src/utils/skills.util.ts
  server/src/utils/user.util.ts
  shared/src/types/post.ts
Labels: bug, enhancement

#21 Auth optimisation
  client/src/app/pages/edit-profile/edit-profile.component.ts
  client/src/app/pages/login/login.component.html
  client/src/app/pages/login/login.component.ts
  client/src/app/pages/profile/profile.component.html
  client/src/app/pages/register/register.component.html
  client/src/app/pages/register/register.component.ts
  server/src/controllers/users.controller.ts
Labels: bug, enhancement

#24 :rocket: IMPROVE : Payment for free product
  client/src/app/pages/resource-details/resource-details.component.html
Labels: bug

#25 Merge create job with main
  client/src/app/components/footer/footer.component.html
  client/src/app/components/header/header.component.html
  client/src/app/components/summary-card/summary-card.component.html
  client/src/app/pages/applicants/applicants.component.html
  client/src/app/pages/create-job/create-job.component.html
  client/src/app/pages/create-job/create-job.component.ts
  client/src/app/pages/create-post/create-post.component.html
  client/src/app/pages/create-resource/create-resource.component.html
  client/src/app/pages/home/home.component.ts
  client/src/app/pages/job-details/job-details.component.html
  client/src/app/pages/profile/profile.component.html
  client/src/app/services/job.service.ts
  client/src/app/views/home/business-view/business-view.component.html
  client/src/app/views/home/user-view/user-view.component.html
  package-lock.json
Labels: bug, enhancement

#26 Minor fixes
  client/src/app/components/footer/footer.component.html
  client/src/app/components/header/header.component.html
  client/src/favicon.ico
  client/src/index.html
Labels: bug
